"""
Django settings for caisses_femmes project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    
    # Local apps
    'gestion_caisses',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'caisses_femmes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestion_caisses.context_processors.app_params',
            ],
        },
    },
]

WSGI_APPLICATION = 'caisses_femmes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Lome'

USE_I18N = True

USE_TZ = True

# Formats d'affichage des dates (Django)
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
# Formats de saisie des dates (Django forms/admin)
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',
]
DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M',
    '%d/%m/%Y %H:%M:%S',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirects
LOGIN_URL = '/gestion-caisses/login/'
LOGIN_REDIRECT_URL = '/gestion-caisses/dashboard/'
LOGOUT_REDIRECT_URL = '/gestion-caisses/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Formats d'affichage et de saisie (DRF)
    'DATETIME_FORMAT': '%d/%m/%Y %H:%M',
    'DATE_FORMAT': '%d/%m/%Y',
    'DATETIME_INPUT_FORMATS': [
        '%d/%m/%Y %H:%M',
        '%d/%m/%Y %H:%M:%S',
        '%Y-%m-%d %H:%M',
        '%Y-%m-%d %H:%M:%S',
        '%Y-%m-%dT%H:%M:%S',
        '%Y-%m-%dT%H:%M:%S.%fZ',
    ],
    'DATE_INPUT_FORMATS': [
        '%d/%m/%Y',
        '%Y-%m-%d',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Autoriser automatiquement ngrok en DEV
if DEBUG:
    # ALLOWED_HOSTS: accepter tous les sous-domaines ngrok
    if isinstance(ALLOWED_HOSTS, (list, tuple)):
        ALLOWED_HOSTS = list(ALLOWED_HOSTS) + ['.ngrok-free.app']
    else:
        ALLOWED_HOSTS = ['.ngrok-free.app']

    # CSRF: faire confiance aux origines ngrok (http/https)
    try:
        CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [
            'https://*.ngrok-free.app',
            'http://*.ngrok-free.app',
        ]
    except NameError:
        CSRF_TRUSTED_ORIGINS = [
            'https://*.ngrok-free.app',
            'http://*.ngrok-free.app',
        ]

    # CORS: autoriser n'importe quel sous-domaine ngrok
    CORS_ALLOWED_ORIGIN_REGEXES = [r'^https?:\/\/.*\.ngrok-free\.app$']

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Session & Cookie security
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HSTS in production
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0 if DEBUG else 31536000, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Session lifetime
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=60*60*8, cast=int)  # 8 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=False, cast=bool)

# Reverse proxy / HTTPS header (enable if behind proxy like Nginx)
if config('USE_X_FORWARDED_PROTO', default=False, cast=bool):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'INFO',
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Jazzmin: configuration de base; couleurs harmonisées

JAZZMIN_SETTINGS = {
	"site_title": "Administration",
	"site_header": "Administration",
	"site_brand": "Administration",
	"welcome_sign": "Connectez-vous",
	"site_logo": "jazzmin/img/default-log.svg",
	"site_icon": "jazzmin/img/default-log.svg",
	"custom_css": "jazzmin/overrides.css",
	"custom_js": None,
	"topmenu_links": [
		{"name": "Tableau de bord", "url": "/gestion-caisses/admin-frontend/", "permissions": ["auth.view_user"]},
	],
}

JAZZMIN_UI_TWEAKS = {
	"navbar": "navbar-dark navbar-purple",
	"no_navbar_border": True,
	"sidebar": "sidebar-dark-purple",
	"theme": "default",
	"dark_mode_theme": None,
	"button_classes": {
		"primary": "btn-primary",
		"secondary": "btn-secondary",
		"info": "btn-info",
		"warning": "btn-warning",
		"danger": "btn-danger",
		"success": "btn-success",
	},
}

# Celery Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Configuration des tâches planifiées
CELERY_BEAT_SCHEDULE = {
    'verifier-prets-en-retard': {
        'task': 'gestion_caisses.tasks.verifier_prets_en_retard',
        'schedule': 3600.0,  # Toutes les heures
    },
    'calculer-statistiques-caisses': {
        'task': 'gestion_caisses.tasks.calculer_statistiques_caisses',
        'schedule': 86400.0,  # Tous les jours
    },
    'nettoyer-audit-logs': {
        'task': 'gestion_caisses.tasks.nettoyer_audit_logs',
        'schedule': 604800.0,  # Toutes les semaines
    },
    'verifier-fonds-insuffisants': {
        'task': 'gestion_caisses.tasks.verifier_fonds_insuffisants',
        'schedule': 43200.0,  # Toutes les 12 heures
    },
    'generer-rapport-mensuel': {
        'task': 'gestion_caisses.tasks.generer_rapport_mensuel',
        'schedule': 2592000.0,  # Tous les mois
    },
    'envoyer-notifications-retard': {
        'task': 'gestion_caisses.tasks.envoyer_notifications_retard',
        'schedule': 86400.0,  # Tous les jours
    },
    'verifier-cloture-exercices-prochaine': {
        'task': 'gestion_caisses.tasks.verifier_cloture_exercices_prochaine',
        'schedule': 86400.0,  # Tous les jours
    },
    'cloturer-exercices-automatiquement': {
        'task': 'gestion_caisses.tasks.cloturer_exercices_automatiquement',
        'schedule': 86400.0,  # Tous les jours
    },
}
