# Generated by Django 5.2.5 on 2025-08-12 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('NOTIFICATION', 'Notification')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_adresse',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modele',
            field=models.CharField(max_length=50, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objet_id',
            field=models.PositiveIntegerField(verbose_name="ID de l'objet"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_ATTENTE_ADMIN', 'En attente validation admin'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('BLOQUE', 'Bloqué'), ('EN_COURS', 'En cours'), ('REMBOURSE', 'Remboursé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('DEMANDE_PRET', 'Demande de prêt'), ('VALIDATION_PRET', 'Validation de prêt'), ('REJET_PRET', 'Rejet de prêt'), ('ATTENTE_PRET', 'Mise en attente de prêt'), ('OCTROI_PRET', 'Octroi de prêt'), ('ALERTE_FOND', 'Alerte fond insuffisant'), ('ALERTE_RETARD', 'Alerte prêt en retard'), ('SYSTEME', 'Notification système')], max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('TRAITE', 'Traité')], default='NON_LU', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('lien_action', models.CharField(blank=True, max_length=200, verbose_name="Lien d'action")),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_caisses.caisse', verbose_name='Caisse concernée')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('pret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_caisses.pret', verbose_name='Prêt concerné')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
