# Generated by Django 5.2.5 on 2025-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0003_membre_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='sexe',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], default='F', max_length=1),
        ),
    ]
