# Generated by Django 5.2.5 on 2025-08-15 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def create_default_agent(apps, schema_editor):
    """Crée un agent par défaut pour les caisses existantes"""
    Agent = apps.get_model('gestion_caisses', 'Agent')
    Region = apps.get_model('gestion_caisses', 'Region')
    Prefecture = apps.get_model('gestion_caisses', 'Prefecture')
    
    # Créer un agent par défaut
    default_agent = Agent.objects.create(
        nom="Agent",
        prenoms="Par Défaut",
        date_naissance=timezone.now().date(),
        adresse="À définir",
        numero_telephone="À définir",
        email="",
        matricule="AGENT_DEFAULT",
        date_embauche=timezone.now().date(),
        statut='ACTIF',
        notes="Agent créé automatiquement pour les caisses existantes"
    )


def assign_default_agent_to_caisses(apps, schema_editor):
    """Assigne l'agent par défaut à toutes les caisses existantes"""
    Caisse = apps.get_model('gestion_caisses', 'Caisse')
    Agent = apps.get_model('gestion_caisses', 'Agent')
    
    # Récupérer l'agent par défaut
    default_agent = Agent.objects.get(matricule="AGENT_DEFAULT")
    
    # Assigner cet agent à toutes les caisses qui n'en ont pas
    Caisse.objects.filter(agent__isnull=True).update(agent=default_agent)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0004_membre_sexe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('matricule', models.CharField(help_text="Matricule unique de l'agent", max_length=20, unique=True)),
                ('date_embauche', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='gestion_caisses.prefecture')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='gestion_caisses.region')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['nom', 'prenoms'],
            },
        ),
        # Créer l'agent par défaut
        migrations.RunPython(create_default_agent, reverse_code=migrations.RunPython.noop),
        # Ajouter le champ agent sans contrainte de clé étrangère d'abord
        migrations.AddField(
            model_name='caisse',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caisses', to='gestion_caisses.agent', verbose_name='Agent responsable'),
        ),
        # Assigner l'agent par défaut aux caisses existantes
        migrations.RunPython(assign_default_agent_to_caisses, reverse_code=migrations.RunPython.noop),
        # Rendre le champ obligatoire
        migrations.AlterField(
            model_name='caisse',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses', to='gestion_caisses.agent', verbose_name='Agent responsable'),
        ),
    ]
