# Generated by Django 5.2.5 on 2025-08-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0005_agent_caisse_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, help_text="Numéro de carte d'électeur unique de l'agent", max_length=20, null=True, unique=True),
        ),
    ]
