# Generated by Django 5.2.5 on 2025-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0007_make_numero_carte_electeur_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(editable=False, help_text="Matricule unique de l'agent (généré automatiquement)", max_length=20, unique=True),
        ),
    ]
