# Generated by Django 5.2.5 on 2025-08-17 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0008_make_matricule_auto_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénoms')),
                ('numero_carte_electeur', models.CharField(max_length=20, unique=True, verbose_name="Numéro de carte d'électeur")),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('numero_telephone', models.CharField(max_length=8, verbose_name='Numéro de téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_president_general/', verbose_name='Photo')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures_president_general/', verbose_name='Signature')),
                ('date_nomination', models.DateTimeField(auto_now_add=True, verbose_name='Date de nomination')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Président Général',
                'verbose_name_plural': 'Présidents Généraux',
                'ordering': ['-date_nomination'],
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures_membres/', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='numero_telephone',
            field=models.CharField(help_text='Numéro de téléphone à 8 chiffres (format togolais)', max_length=8, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 8 chiffres (format togolais)', regex='^[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_telephone',
            field=models.CharField(help_text='Numéro de téléphone à 8 chiffres (format togolais)', max_length=8, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 8 chiffres (format togolais)', regex='^[0-9]{8}$')]),
        ),
    ]
