# Generated by Django 5.2.5 on 2025-08-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0009_presidentgeneral_membre_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(default='CAISSE DE SOLIDARITÉ', max_length=200, verbose_name="Nom de l'application")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name="Logo de l'application")),
                ('description_application', models.TextField(blank=True, verbose_name="Description de l'application")),
                ('version_application', models.CharField(default='1.0.0', max_length=20, verbose_name="Version de l'application")),
                ('telephone_principal', models.CharField(blank=True, max_length=20, verbose_name='Téléphone principal')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('siege_social', models.TextField(blank=True, verbose_name='Siège social')),
                ('adresse_postale', models.CharField(blank=True, max_length=200, verbose_name='Adresse postale')),
                ('boite_postale', models.CharField(blank=True, max_length=20, verbose_name='Boîte postale')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Togo', max_length=100, verbose_name='Pays')),
                ('nom_president_general', models.CharField(blank=True, max_length=200, verbose_name='Nom du Président Général/PDG')),
                ('titre_president_general', models.CharField(default='Président Général', max_length=100, verbose_name='Titre du Président Général')),
                ('signature_president_general', models.ImageField(blank=True, null=True, upload_to='signatures_pdg/', verbose_name='Signature du Président Général')),
                ('nom_directeur_technique', models.CharField(blank=True, max_length=200, verbose_name='Nom du Directeur Technique')),
                ('nom_directeur_financier', models.CharField(blank=True, max_length=200, verbose_name='Nom du Directeur Financier')),
                ('nom_directeur_administratif', models.CharField(blank=True, max_length=200, verbose_name='Nom du Directeur Administratif')),
                ('numero_agrement', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'agrément")),
                ('date_agrement', models.DateField(blank=True, null=True, verbose_name="Date d'agrément")),
                ('autorite_agrement', models.CharField(blank=True, max_length=200, verbose_name="Autorité d'agrément")),
                ('devise', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('langue_par_defaut', models.CharField(default='fr', max_length=10, verbose_name='Langue par défaut')),
                ('fuseau_horaire', models.CharField(default='Africa/Lome', max_length=50, verbose_name='Fuseau horaire')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='Texte de copyright')),
                ('mentions_legales', models.TextField(blank=True, verbose_name='Mentions légales')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Paramètres actifs')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
