# Generated by Django 5.2.5 on 2025-08-18 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0010_parametre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Caisse Générale', max_length=100, verbose_name='Nom')),
                ('solde_reserve', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde de réserve')),
                ('solde_total_caisses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Somme des caisses')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Caisse Générale',
                'verbose_name_plural': 'Caisse Générale',
            },
        ),
        migrations.CreateModel(
            name='CaisseGeneraleMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (crédit réserve)'), ('SORTIE', 'Sortie (débit réserve)'), ('ALIMENTATION_CAISSE', "Alimentation d'une caisse")], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_avant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_apres', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('caisse_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentations_recuees', to='gestion_caisses.caisse')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement caisse générale',
                'verbose_name_plural': 'Mouvements caisse générale',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
