# Generated by Django 5.2.5 on 2025-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0011_caissegenerale_caissegeneralemouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='date_fin_pret',
            field=models.DateField(blank=True, null=True),
        ),
    ]
