# Generated by Django 5.2.5 on 2025-08-18 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0012_pret_date_fin_pret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('general', 'Rapport Général'), ('financier', 'Rapport Financier'), ('prets', 'Rapport des Prêts'), ('membres', 'Rapport des Membres'), ('echeances', 'Rapport des Échéances')], max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('GENERE', 'Généré'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('notes', models.TextField(blank=True)),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='gestion_caisses.caisse')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport d’activité',
                'verbose_name_plural': 'Rapports d’activité',
                'ordering': ['-date_generation'],
            },
        ),
    ]
