# Generated by Django 5.2.5 on 2025-08-23 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0012_pret_date_fin_pret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementfond',
            name='caisse_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_transferts_recus', to='gestion_caisses.caisse'),
        ),
        migrations.AddField(
            model_name='mouvementfond',
            name='caisse_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_transferts_envoyes', to='gestion_caisses.caisse'),
        ),
        migrations.AlterField(
            model_name='mouvementfond',
            name='type_mouvement',
            field=models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('DECAISSEMENT', 'Décaissement'), ('REMBOURSEMENT', 'Remboursement'), ('FRAIS', 'Frais'), ('AUTRE', 'Autre'), ('TRANSFERT_VERS_CAISSE', 'Transfert vers une autre caisse'), ('TRANSFERT_VERS_GENERALE', 'Transfert vers la caisse générale'), ('RECEPTION_CAISSE', "Réception d'un transfert d'une autre caisse"), ('RECEPTION_GENERALE', "Réception d'un transfert de la caisse générale")], max_length=30),
        ),
        migrations.CreateModel(
            name='TransfertCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transfert', models.CharField(choices=[('CAISSE_VERS_CAISSE', "Transfert d'une caisse vers une autre caisse"), ('CAISSE_VERS_GENERALE', "Transfert d'une caisse vers la caisse générale"), ('GENERALE_VERS_CAISSE', 'Transfert de la caisse générale vers une caisse')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_transfert', models.DateTimeField(auto_now_add=True, verbose_name='Date du transfert')),
                ('description', models.TextField(blank=True, verbose_name='Description du transfert')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('caisse_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_recus', to='gestion_caisses.caisse', verbose_name='Caisse destination')),
                ('caisse_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_envoyes', to='gestion_caisses.caisse', verbose_name='Caisse source')),
                ('mouvement_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_destination', to='gestion_caisses.mouvementfond', verbose_name='Mouvement destination')),
                ('mouvement_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfert_source', to='gestion_caisses.mouvementfond', verbose_name='Mouvement source')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur responsable')),
            ],
            options={
                'verbose_name': 'Transfert entre caisses',
                'verbose_name_plural': 'Transferts entre caisses',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
