# Generated by Django 5.2.5 on 2025-08-27 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0015_admindashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertcaisse',
            name='caisse_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_envoyes', to='gestion_caisses.caisse', verbose_name='Caisse source'),
        ),
        migrations.CreateModel(
            name='SeanceReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='gestion_caisses.caisse')),
            ],
            options={
                'verbose_name': 'Séance de réunion',
                'verbose_name_plural': 'Séances de réunion',
                'ordering': ['-date_seance', '-date_creation'],
                'unique_together': {('caisse', 'date_seance', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cotisation', models.DateTimeField(auto_now_add=True)),
                ('prix_tempon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_solidarite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_fondation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalite_emprunt_retard', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion_caisses.caisse')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion_caisses.membre')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion_caisses.seancereunion')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_cotisation'],
                'indexes': [models.Index(fields=['caisse', 'membre'], name='gestion_cai_caisse__194eee_idx'), models.Index(fields=['date_cotisation'], name='gestion_cai_date_co_646b2f_idx')],
            },
        ),
    ]
