# Generated by Django 5.2.5 on 2025-08-29 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0016_alter_transfertcaisse_caisse_source_seancereunion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('SOLIDARITE', 'Frais de solidarité'), ('PENALITE', 'Frais de pénalités'), ('AUTRE', 'Autre dépense')], default='AUTRE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('justificatif', models.TextField(help_text='Justification de la dépense')),
                ('date_depense', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=20)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('notes_approbation', models.TextField(blank=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_approuvees', to='gestion_caisses.membre')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='gestion_caisses.caisse')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_responsable', to='gestion_caisses.membre')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-date_creation'],
                'indexes': [models.Index(fields=['caisse', 'categorie'], name='gestion_cai_caisse__91c89b_idx'), models.Index(fields=['date_depense'], name='gestion_cai_date_de_981e53_idx'), models.Index(fields=['statut'], name='gestion_cai_statut_8830b5_idx')],
            },
        ),
    ]
