# Generated by Django 5.2.5 on 2025-08-29 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0017_depense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('MEMBRES', 'Liste des membres'), ('PRETS', 'Rapport des prêts'), ('COTISATIONS', 'Rapport des cotisations'), ('DEPENSES', 'Rapport des dépenses'), ('GENERAL', 'Rapport général'), ('CAISSE_GENERALE', 'Rapport caisse générale')], max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('GENERE', 'Généré'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_activite', to='gestion_caisses.caisse')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Rapport d'activité",
                'verbose_name_plural': "Rapports d'activité",
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['type_rapport'], name='gestion_cai_type_ra_b18db2_idx'), models.Index(fields=['caisse'], name='gestion_cai_caisse__a551e8_idx'), models.Index(fields=['statut'], name='gestion_cai_statut_9f9586_idx'), models.Index(fields=['date_creation'], name='gestion_cai_date_cr_a09fad_idx')],
            },
        ),
    ]
