# Generated by Django 5.2.5 on 2025-08-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0018_rapportactivite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='beneficiaires',
            field=models.TextField(blank=True, help_text='Bénéficiaires de cette dépense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='date_execution',
            field=models.DateField(blank=True, help_text="Date d'exécution effective", null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='est_urgente',
            field=models.BooleanField(default=False, help_text='Marquer comme dépense urgente'),
        ),
        migrations.AddField(
            model_name='depense',
            name='montant_initial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant initialement demandé (si différent du montant final)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='montant_seuil_approbation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant seuil pour l'approbation automatique", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='necessite_approbation',
            field=models.BooleanField(default=True, help_text='Nécessite une approbation'),
        ),
        migrations.AddField(
            model_name='depense',
            name='notes_execution',
            field=models.TextField(blank=True, help_text="Notes sur l'exécution"),
        ),
        migrations.AddField(
            model_name='depense',
            name='notes_rejet',
            field=models.TextField(blank=True, help_text='Motif du rejet si applicable'),
        ),
        migrations.AddField(
            model_name='depense',
            name='objectif',
            field=models.TextField(blank=True, help_text='Objectif et justification de la dépense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='pieces_justificatives',
            field=models.TextField(blank=True, help_text='Liste des pièces justificatives'),
        ),
        migrations.AddField(
            model_name='depense',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='titre',
            field=models.CharField(blank=True, help_text='Titre/objet de la dépense', max_length=200),
        ),
        migrations.AddField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('ORDINAIRE', 'Dépense ordinaire'), ('EXTRAORDINAIRE', 'Dépense extraordinaire'), ('URGENTE', 'Dépense urgente')], default='ORDINAIRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='approuve_par',
            field=models.ForeignKey(blank=True, help_text='Membre qui a approuvé la dépense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_approuvees', to='gestion_caisses.membre'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('SOLIDARITE', 'Frais de solidarité'), ('PENALITE', 'Frais de pénalités'), ('ADMINISTRATIF', 'Frais administratifs'), ('FORMATION', 'Formation et sensibilisation'), ('SANTE', 'Santé et bien-être'), ('EDUCATION', 'Éducation et alphabétisation'), ('AGRICULTURE', 'Agriculture et élevage'), ('COMMERCE', 'Commerce et artisanat'), ('INFRASTRUCTURE', 'Infrastructure et équipement'), ('URGENCE', 'Urgence et secours'), ('AUTRE', 'Autre dépense')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date_depense',
            field=models.DateField(help_text='Date de la dépense'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.TextField(help_text='Description détaillée de la dépense'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='justificatif',
            field=models.TextField(help_text='Justification détaillée de la dépense'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant de la dépense en FCFA', max_digits=15),
        ),
        migrations.AlterField(
            model_name='depense',
            name='notes_approbation',
            field=models.TextField(blank=True, help_text="Commentaires lors de l'approbation"),
        ),
        migrations.AlterField(
            model_name='depense',
            name='responsable',
            field=models.ForeignKey(help_text="Membre responsable de l'exécution de la dépense", on_delete=django.db.models.deletion.CASCADE, related_name='depenses_responsable', to='gestion_caisses.membre'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé la dépense', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['priorite'], name='gestion_cai_priorit_b898f0_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['type_depense'], name='gestion_cai_type_de_79e55b_idx'),
        ),
    ]
