# Generated by Django 5.2.5 on 2025-09-03 08:01

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0019_depense_beneficiaires_depense_date_execution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-datedepense', '-date_creation'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.RemoveIndex(
            model_name='depense',
            name='gestion_cai_caisse__91c89b_idx',
        ),
        migrations.RemoveIndex(
            model_name='depense',
            name='gestion_cai_date_de_981e53_idx',
        ),
        migrations.RemoveIndex(
            model_name='depense',
            name='gestion_cai_statut_8830b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='depense',
            name='gestion_cai_priorit_b898f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='depense',
            name='gestion_cai_type_de_79e55b_idx',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='approuve_par',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='beneficiaires',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='date_approbation',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='date_depense',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='date_execution',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='est_urgente',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='justificatif',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='montant_initial',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='montant_seuil_approbation',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='necessite_approbation',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='notes_approbation',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='notes_execution',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='notes_rejet',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='objectif',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='pieces_justificatives',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='priorite',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='type_depense',
        ),
        migrations.AddField(
            model_name='depense',
            name='Objectifdepense',
            field=models.TextField(blank=True, default='', help_text='Objectif de la dépense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='datedepense',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date de la dépense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='montantdepense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la dépense en FCFA', max_digits=15),
        ),
        migrations.AddField(
            model_name='depense',
            name='observation',
            field=models.TextField(blank=True, help_text='Observation (optionnel)'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['caisse'], name='gestion_cai_caisse__220dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['datedepense'], name='gestion_cai_datedep_dd5e7a_idx'),
        ),
    ]
