# Generated by Django 5.2.5 on 2025-09-03 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0020_alter_depense_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaireAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, help_text='Salaire fixe mensuel', max_digits=15)),
                ('bonus_caisses', models.DecimalField(decimal_places=2, default=0, help_text='Bonus basé sur les nouvelles caisses créées', max_digits=15)),
                ('prime_performance', models.DecimalField(decimal_places=2, default=0, help_text='Prime de performance additionnelle', max_digits=15)),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, help_text='Mode de paiement (virement, chèque, espèce, etc.)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='gestion_caisses.agent')),
            ],
            options={
                'verbose_name': 'Salaire Agent',
                'verbose_name_plural': 'Salaires Agents',
                'ordering': ['-annee', '-mois', 'agent'],
            },
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fiche', models.CharField(choices=[('MOIS', 'Fiche mensuelle'), ('TRIMESTRE', 'Fiche trimestrielle'), ('ANNEE', 'Fiche annuelle')], default='MOIS', max_length=20)),
                ('nom_agent', models.CharField(max_length=300)),
                ('matricule', models.CharField(max_length=50)),
                ('poste', models.CharField(default='Agent de terrain', max_length=100)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bonus_caisses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prime_performance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_brut', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('nombre_nouvelles_caisses', models.IntegerField(default=0)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='fiches_paie/')),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_paie_generes', to=settings.AUTH_USER_MODEL)),
                ('salaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_paie', to='gestion_caisses.salaireagent')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-annee', '-mois', 'nom_agent'],
            },
        ),
        migrations.AddIndex(
            model_name='salaireagent',
            index=models.Index(fields=['agent'], name='gestion_cai_agent_i_6c2123_idx'),
        ),
        migrations.AddIndex(
            model_name='salaireagent',
            index=models.Index(fields=['mois', 'annee'], name='gestion_cai_mois_121e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='salaireagent',
            index=models.Index(fields=['statut'], name='gestion_cai_statut_8848a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaireagent',
            unique_together={('agent', 'mois', 'annee')},
        ),
        migrations.AddIndex(
            model_name='fichepaie',
            index=models.Index(fields=['salaire'], name='gestion_cai_salaire_ec8e84_idx'),
        ),
        migrations.AddIndex(
            model_name='fichepaie',
            index=models.Index(fields=['mois', 'annee'], name='gestion_cai_mois_a56a93_idx'),
        ),
        migrations.AddIndex(
            model_name='fichepaie',
            index=models.Index(fields=['date_generation'], name='gestion_cai_date_ge_be3e6a_idx'),
        ),
    ]
