# Generated by Django 5.2.5 on 2025-09-09 11:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0022_membre_carte_electeur_valide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='carte_electeur_valide',
            field=models.BooleanField(default=False, verbose_name="Carte d'électeur valide"),
        ),
        migrations.AddField(
            model_name='agent',
            name='indicatif_telephone',
            field=models.CharField(choices=[('+228', 'Togo'), ('+229', 'Bénin'), ('+233', 'Ghana')], default='+228', help_text='Indicatif du pays du numéro de téléphone', max_length=5),
        ),
        migrations.AddField(
            model_name='agent',
            name='numero_whatsapp',
            field=models.CharField(blank=True, help_text="Numéro WhatsApp (sans indicatif, optionnel). Longueur contrôlée selon l'indicatif.", max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro WhatsApp doit contenir uniquement des chiffres', regex='^[0-9]+$')]),
        ),
        migrations.AddField(
            model_name='agent',
            name='possede_carte_electeur',
            field=models.BooleanField(default=True, verbose_name="Possède une carte d'électeur"),
        ),
        migrations.AddField(
            model_name='agent',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='gestion_caisses.quartier'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='numero_carte_electeur',
            field=models.CharField(help_text="Numéro de carte d'électeur (alphanumérique, 26 caractères max)", max_length=26, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de carte doit être alphanumérique et contenir au plus 26 caractères.', regex='^[A-Za-z0-9]{1,26}$')]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='numero_telephone',
            field=models.CharField(help_text="Numéro de téléphone (sans indicatif). Longueur contrôlée selon l'indicatif.", max_length=12, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir uniquement des chiffres', regex='^[0-9]+$')]),
        ),
    ]
