# Generated by Django 5.2.5 on 2025-09-09 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0023_agent_carte_electeur_valide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='numero_carte_electeur',
            field=models.CharField(help_text="Numéro de carte d'électeur: exactement 26 caractères (A-Z, 0-9, tirets)", max_length=26, unique=True, validators=[django.core.validators.RegexValidator(message="Format invalide. Utiliser exactement 26 caractères (A-Z, 0-9 et '-') sans tiret au début/fin ni doubles tirets.", regex='^(?!-)(?!.*--)(?=.*-)[A-Z0-9-]{26}(?<!-)$')]),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_carte_electeur',
            field=models.CharField(help_text="Numéro de carte d'électeur: exactement 26 caractères (A-Z, 0-9, tirets)", max_length=26, validators=[django.core.validators.RegexValidator(message="Format invalide. Utiliser exactement 26 caractères (A-Z, 0-9 et '-') sans tiret au début/fin ni doubles tirets.", regex='^(?!-)(?!.*--)(?=.*-)[A-Z0-9-]{26}(?<!-)$')]),
        ),
    ]
