# Generated by Django 5.2.5 on 2025-09-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0024_alter_agent_numero_carte_electeur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Calcul automatique: date_debut + 10 mois', null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='gestion_caisses.caisse')),
            ],
            options={
                'verbose_name': 'Exercice de caisse',
                'verbose_name_plural': 'Exercices de caisse',
                'ordering': ['-date_debut', '-date_creation'],
                'indexes': [models.Index(fields=['caisse'], name='gestion_cai_caisse__e76f3e_idx'), models.Index(fields=['statut'], name='gestion_cai_statut_dc4c59_idx'), models.Index(fields=['date_debut'], name='gestion_cai_date_de_ce0abc_idx')],
            },
        ),
    ]
