# Generated by Django 5.2.5 on 2025-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0026_alter_caisse_nom_association_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicecaisse',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Calcul automatique: date_debut + 12 mois', null=True),
        ),
    ]
