# Generated by Django 5.2.5 on 2025-09-17 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0027_alter_exercicecaisse_date_fin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives_exercices', to='gestion_caisses.caisse')),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='gestion_caisses.exercicecaisse')),
            ],
            options={
                'verbose_name': "Archive d'exercice",
                'verbose_name_plural': "Archives d'exercices",
                'ordering': ['-date_fin', '-archived_at'],
                'indexes': [models.Index(fields=['caisse'], name='gestion_cai_caisse__dbb447_idx'), models.Index(fields=['date_debut'], name='gestion_cai_date_de_28433d_idx'), models.Index(fields=['date_fin'], name='gestion_cai_date_fi_4c2b0f_idx')],
            },
        ),
    ]
