# Generated by Django 5.2.5 on 2025-11-10 16:23

import gestion_caisses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0028_exercicearchive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membre',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, help_text="Numéro de carte d'électeur: exactement 26 caractères (A-Z, 0-9, tirets) - Optionnel", max_length=26, null=True, unique=True, validators=[gestion_caisses.models.validate_carte_electeur_optional]),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, help_text="Numéro de carte d'électeur: exactement 26 caractères (A-Z, 0-9, tirets) - Optionnel", max_length=26, null=True, validators=[gestion_caisses.models.validate_carte_electeur_optional]),
        ),
    ]
