# Generated by Django 5.2.5 on 2025-11-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0029_alter_membre_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_caisses.exercicecaisse', verbose_name='Exercice concerné'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('DEMANDE_PRET', 'Demande de prêt'), ('VALIDATION_PRET', 'Validation de prêt'), ('REJET_PRET', 'Rejet de prêt'), ('ATTENTE_PRET', 'Mise en attente de prêt'), ('OCTROI_PRET', 'Octroi de prêt'), ('ALERTE_FOND', 'Alerte fond insuffisant'), ('ALERTE_RETARD', 'Alerte prêt en retard'), ('CLOTURE_EXERCICE_PROCHAIN', "Clôture d'exercice prochaine"), ('CLOTURE_EXERCICE', "Clôture d'exercice"), ('SYSTEME', 'Notification système')], max_length=30, verbose_name='Type'),
        ),
    ]
