# Generated by Django 5.2.5 on 2025-11-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0030_notification_exercice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FKMBoard',
            fields=[
            ],
            options={
                'verbose_name': '0 FKM Board',
                'verbose_name_plural': '0 FKM Board',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_caisses.fichepaie',),
        ),
    ]
