# Generated by Django 5.2.5

import gestion_caisses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisses', '0031_fkmboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, help_text="Numéro de carte d'électeur: exactement 27 caractères (A-Z, 0-9, tirets) - Optionnel", max_length=27, null=True, unique=True, validators=[gestion_caisses.models.validate_carte_electeur_optional]),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, help_text="Numéro de carte d'électeur: exactement 27 caractères (A-Z, 0-9, tirets) - Optionnel", max_length=27, null=True, validators=[gestion_caisses.models.validate_carte_electeur_optional]),
        ),
    ]

